AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Microservicio de Delivery - Gestion de asignacion y actualizacion de estados de pedidos

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    MemorySize: 256
    Environment:
      Variables:
        DELIVERY_TABLE: !Ref DeliveryTable
        CONNECTIONS_TABLE: !Ref ConnectionsTable
        COCINEROS_TABLE: !Ref CocinerosTable
        EVENT_BUS_NAME: !Ref DeliveryEventBus
        WS_ENDPOINT: !Sub "https://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
        SERVICE_NAME: delivery-service
        LOG_LEVEL: INFO

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Stage de despliegue

Resources:
  # ============================================
  # DynamoDB Tables
  # ============================================
  DeliveryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "delivery-${Stage}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
        - AttributeName: restaurantId
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: RestaurantIdIndex
          KeySchema:
            - AttributeName: restaurantId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: StatusIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "delivery-connections-${Stage}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
        - AttributeName: restaurantId
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: RestaurantIdIndex
          KeySchema:
            - AttributeName: restaurantId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  CocinerosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "cocineros-${Stage}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: cocineroId
          AttributeType: S
        - AttributeName: restaurantId
          AttributeType: S
      KeySchema:
        - AttributeName: cocineroId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: RestaurantIdIndex
          KeySchema:
            - AttributeName: restaurantId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  # ============================================
  # EventBridge
  # ============================================
  DeliveryEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub "delivery-event-bus-${Stage}"

  # Rule para iniciar Step Function cuando llega PagoConfirmado
  PagoConfirmadoRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "pago-confirmado-rule-${Stage}"
      EventBusName: !Ref DeliveryEventBus
      EventPattern:
        source:
          - "orders.service"
        detail-type:
          - "PagoConfirmado"
      State: ENABLED
      Targets:
        - Id: StartDeliveryStateMachine
          Arn: !Ref DeliveryStateMachine
          RoleArn: !GetAtt EventBridgeToStepFunctionsRole.Arn

  # Rule para eventos de delivery hacia el event handler
  DeliveryEventsRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "delivery-events-rule-${Stage}"
      EventBusName: !Ref DeliveryEventBus
      EventPattern:
        source:
          - "delivery.service"
          - "kitchen.service"
          - "dispatch.service"
        detail-type:
          - "ComidaPreparada"
          - "Despachado"
          - "Entregado"
      State: ENABLED
      Targets:
        - Id: DeliveryEventHandler
          Arn: !GetAtt EventHandlerFunction.Arn

  # ============================================
  # Step Functions
  # ============================================
  DeliveryStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub "delivery-state-machine-${Stage}"
      DefinitionUri: ../delivery.asl.json
      DefinitionSubstitutions:
        AsignarCocineroArn: !GetAtt AsignarCocineroFunction.Arn
        AsignarDespachadorArn: !GetAtt AsignarDespachadorFunction.Arn
        AsignarRepartidorArn: !GetAtt AsignarRepartidorFunction.Arn
        ConfirmarEntregaArn: !GetAtt ConfirmarEntregaFunction.Arn
        EventBusName: !Ref DeliveryEventBus
        DeliveryApiUrl: !Sub "https://${DeliveryApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref AsignarCocineroFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref AsignarDespachadorFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref AsignarRepartidorFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ConfirmarEntregaFunction
        - EventBridgePutEventsPolicy:
            EventBusName: !Ref DeliveryEventBus

  # ============================================
  # Lambda Functions
  # ============================================
  AsignarCocineroFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "AsignarCocinero-${Stage}"
      CodeUri: ../dist/handlers/
      Handler: Lambda_AsignarCocinero.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DeliveryTable
        - DynamoDBReadPolicy:
            TableName: !Ref CocinerosTable
        - Statement:
            - Effect: Allow
              Action:
                - states:SendTaskSuccess
                - states:SendTaskFailure
              Resource: "*"

  AsignarDespachadorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "AsignarDespachador-${Stage}"
      CodeUri: ../dist/handlers/
      Handler: Lambda_AsignarDespachador.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DeliveryTable

  AsignarRepartidorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "AsignarRepartidor-${Stage}"
      CodeUri: ../dist/handlers/
      Handler: Lambda_AsignarRepartidor.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DeliveryTable

  ConfirmarEntregaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ConfirmarEntrega-${Stage}"
      CodeUri: ../dist/handlers/
      Handler: Lambda_ConfirmarEntrega.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DeliveryTable
        - Statement:
            - Effect: Allow
              Action:
                - states:SendTaskSuccess
                - states:SendTaskFailure
              Resource: "*"

  # API REST para confirmar entregas
  DeliveryApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "delivery-api-${Stage}"
      StageName: !Ref Stage
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
        AllowOrigin: "'*'"

  ConfirmarEntregaApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ConfirmarEntregaApi-${Stage}"
      CodeUri: ../dist/handlers/
      Handler: api_confirmar_entrega.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DeliveryTable
        - Statement:
            - Effect: Allow
              Action:
                - states:SendTaskSuccess
                - states:SendTaskFailure
              Resource: "*"
      Events:
        ConfirmarEntrega:
          Type: Api
          Properties:
            RestApiId: !Ref DeliveryApi
            Path: /delivery/{orderId}/confirm
            Method: POST
        GetDeliveryStatus:
          Type: Api
          Properties:
            RestApiId: !Ref DeliveryApi
            Path: /delivery/{orderId}
            Method: GET

  EventHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "DeliveryEventHandler-${Stage}"
      CodeUri: ../dist/handlers/
      Handler: event_handler.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DeliveryTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionsTable
        - Statement:
            - Effect: Allow
              Action:
                - states:SendTaskSuccess
                - states:SendTaskFailure
              Resource: "*"
            - Effect: Allow
              Action:
                - execute-api:ManageConnections
              Resource: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*"

  EventHandlerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref EventHandlerFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt DeliveryEventsRule.Arn

  # ============================================
  # WebSocket API
  # ============================================
  WebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub "delivery-websocket-${Stage}"
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $connect
      AuthorizationType: NONE
      Target: !Sub "integrations/${ConnectIntegration}"

  ConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketConnectFunction.Arn}/invocations"

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $disconnect
      AuthorizationType: NONE
      Target: !Sub "integrations/${DisconnectIntegration}"

  DisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketDisconnectFunction.Arn}/invocations"

  WebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref WebSocketApi
      StageName: !Ref Stage
      AutoDeploy: true

  WebSocketConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "WS-Connect-${Stage}"
      CodeUri: ../dist/websocket/
      Handler: connect.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionsTable

  WebSocketConnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebSocketConnectFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*/$connect"

  WebSocketDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "WS-Disconnect-${Stage}"
      CodeUri: ../dist/websocket/
      Handler: disconnect.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionsTable

  WebSocketDisconnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebSocketDisconnectFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*/$disconnect"

  # ============================================
  # IAM Roles
  # ============================================
  EventBridgeToStepFunctionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "EventBridgeToStepFunctions-${Stage}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StartStateMachine
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: states:StartExecution
                Resource: !Ref DeliveryStateMachine

Outputs:
  DeliveryTableName:
    Description: Nombre de la tabla DynamoDB de Delivery
    Value: !Ref DeliveryTable
    Export:
      Name: !Sub "${AWS::StackName}-DeliveryTable"

  ConnectionsTableName:
    Description: Nombre de la tabla DynamoDB de Conexiones WebSocket
    Value: !Ref ConnectionsTable
    Export:
      Name: !Sub "${AWS::StackName}-ConnectionsTable"

  DeliveryEventBusName:
    Description: Nombre del Event Bus
    Value: !Ref DeliveryEventBus
    Export:
      Name: !Sub "${AWS::StackName}-EventBus"

  DeliveryEventBusArn:
    Description: ARN del Event Bus para integracion con otros microservicios
    Value: !GetAtt DeliveryEventBus.Arn
    Export:
      Name: !Sub "${AWS::StackName}-EventBusArn"

  StateMachineArn:
    Description: ARN de la Step Function de Delivery
    Value: !Ref DeliveryStateMachine
    Export:
      Name: !Sub "${AWS::StackName}-StateMachineArn"

  WebSocketUrl:
    Description: URL del WebSocket API
    Value: !Sub "wss://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
    Export:
      Name: !Sub "${AWS::StackName}-WebSocketUrl"

  DeliveryApiUrl:
    Description: URL de la API REST de Delivery
    Value: !Sub "https://${DeliveryApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"
